server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    prefer-ip-address: true
